spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/paascloud_omc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-omc
      consumerGroup: CID_OMC
      producerGroup: PID_OMC