spring:
  datasource:
    url: jdbc:mysql://118.24.75.162:3306/paascloud_opc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-opc
      consumerGroup: CID_OPC
      producerGroup: PID_OPC